id: P006952
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1GS91829
  title: རེབ་གོང་ཡུལ་སྐོར་ཟིན་ཐོ
  author: ''
  volumes:
    760a5110ac934a229c05081b1d19d92a:
      image_group_id: I00KG07099
      title: Volume 1 of reb gong yul skor zin tho
      volume_number: 1
      total_pages: 642
      base_file: v001.txt
