id: P006952
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS91829
  title: རེབ་གོང་ཡུལ་སྐོར་ཟིན་ཐོ
  author: ''
  volumes:
    833aa65cc7c04e909b55397099ee2344:
      image_group_id: I00KG07099
      title: ''
      volume_number: 1
      total_pages: 642
ebook_metadata:
  title: རེབ་གོང་ཡུལ་སྐོར་ཟིན་ཐོ
  author: ''
  sku: P006952
  cover: cover.jpg
  layers:
  - pagination
